spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/multi_module_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wonoh
    password: dnjsdh44
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate:
      SQL: debug
      type:
        descriptor.sql: trace